# Generated by Django 5.0.2 on 2024-03-29 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_source', models.CharField(choices=[('Home', 'Home'), ('Restaurant', 'Restaurant'), ('Other', 'Other')], default='Home', max_length=20)),
                ('restaurant', models.CharField(max_length=200)),
                ('food_type', models.CharField(choices=[('Veg', 'Veg'), ('NonVeg', 'NonVeg'), ('Both', 'Both')], default='Veg', max_length=20)),
                ('food_description', models.CharField(max_length=500)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('image_food', models.ImageField(upload_to='imgs/')),
            ],
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mealsmodel')),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
